version: "3"

networks:
  fintech-backend:
    external: true

volumes:
  ft-mysql-data:
  ft-mongo-data:

services:
  ft-api:
    container_name: ft-api
    image: ft-api
    build:
      context: .
      dockerfile: .docker/golang/api/Dockerfile
    volumes:
      - .:/go/src/github.com/Sharykhin/fin-tech
    env_file:
      - ./.docker/golang/api/.env
    ports:
      - 8003:8003
    depends_on:
      - ft-mysql
      - ft-mongo
    links:
      - ft-mysql
      - ft-mongo
    networks:
      - fintech-backend

  ft-mysql:
    container_name: ft-mysql
    image: ft-mysql
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ft-mysql-data:/var/lib/mysql
    ports:
      - 3309:3306
    env_file:
      - ./.docker/mysql/.env
    networks:
      - fintech-backend

  ft-mongo:
    container_name: ft-mongo
    image: mongo:4.0.6
    ports:
      - 27017:27017
    env_file:
      - ./.docker/mongo/.env
    volumes:
      - ft-mongo-data:/data/db
    networks:
      - fintech-backend
